# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/Documents/research/amass_inverse_dynamics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/Documents/research/amass_inverse_dynamics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/Documents/research/amass_inverse_dynamics/CMakeFiles /home/kevin/Documents/research/amass_inverse_dynamics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/Documents/research/amass_inverse_dynamics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named inverse.out

# Build rule for target.
inverse.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inverse.out
.PHONY : inverse.out

# fast build rule for target.
inverse.out/fast:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/build
.PHONY : inverse.out/fast

# target to build an object file
src/BVHData.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/BVHData.o
.PHONY : src/BVHData.o

# target to preprocess a source file
src/BVHData.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/BVHData.i
.PHONY : src/BVHData.i

# target to generate assembly for a file
src/BVHData.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/BVHData.s
.PHONY : src/BVHData.s

# target to build an object file
src/c_butterworth/c_butterworth.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/c_butterworth.o
.PHONY : src/c_butterworth/c_butterworth.o

# target to preprocess a source file
src/c_butterworth/c_butterworth.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/c_butterworth.i
.PHONY : src/c_butterworth/c_butterworth.i

# target to generate assembly for a file
src/c_butterworth/c_butterworth.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/c_butterworth.s
.PHONY : src/c_butterworth/c_butterworth.s

# target to build an object file
src/c_butterworth/rtGetInf.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rtGetInf.o
.PHONY : src/c_butterworth/rtGetInf.o

# target to preprocess a source file
src/c_butterworth/rtGetInf.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rtGetInf.i
.PHONY : src/c_butterworth/rtGetInf.i

# target to generate assembly for a file
src/c_butterworth/rtGetInf.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rtGetInf.s
.PHONY : src/c_butterworth/rtGetInf.s

# target to build an object file
src/c_butterworth/rtGetNaN.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rtGetNaN.o
.PHONY : src/c_butterworth/rtGetNaN.o

# target to preprocess a source file
src/c_butterworth/rtGetNaN.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rtGetNaN.i
.PHONY : src/c_butterworth/rtGetNaN.i

# target to generate assembly for a file
src/c_butterworth/rtGetNaN.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rtGetNaN.s
.PHONY : src/c_butterworth/rtGetNaN.s

# target to build an object file
src/c_butterworth/rt_nonfinite.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rt_nonfinite.o
.PHONY : src/c_butterworth/rt_nonfinite.o

# target to preprocess a source file
src/c_butterworth/rt_nonfinite.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rt_nonfinite.i
.PHONY : src/c_butterworth/rt_nonfinite.i

# target to generate assembly for a file
src/c_butterworth/rt_nonfinite.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/c_butterworth/rt_nonfinite.s
.PHONY : src/c_butterworth/rt_nonfinite.s

# target to build an object file
src/ext/alglibinternal.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/alglibinternal.o
.PHONY : src/ext/alglibinternal.o

# target to preprocess a source file
src/ext/alglibinternal.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/alglibinternal.i
.PHONY : src/ext/alglibinternal.i

# target to generate assembly for a file
src/ext/alglibinternal.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/alglibinternal.s
.PHONY : src/ext/alglibinternal.s

# target to build an object file
src/ext/alglibmisc.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/alglibmisc.o
.PHONY : src/ext/alglibmisc.o

# target to preprocess a source file
src/ext/alglibmisc.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/alglibmisc.i
.PHONY : src/ext/alglibmisc.i

# target to generate assembly for a file
src/ext/alglibmisc.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/alglibmisc.s
.PHONY : src/ext/alglibmisc.s

# target to build an object file
src/ext/ap.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/ap.o
.PHONY : src/ext/ap.o

# target to preprocess a source file
src/ext/ap.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/ap.i
.PHONY : src/ext/ap.i

# target to generate assembly for a file
src/ext/ap.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/ap.s
.PHONY : src/ext/ap.s

# target to build an object file
src/ext/dataanalysis.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/dataanalysis.o
.PHONY : src/ext/dataanalysis.o

# target to preprocess a source file
src/ext/dataanalysis.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/dataanalysis.i
.PHONY : src/ext/dataanalysis.i

# target to generate assembly for a file
src/ext/dataanalysis.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/dataanalysis.s
.PHONY : src/ext/dataanalysis.s

# target to build an object file
src/ext/diffequations.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/diffequations.o
.PHONY : src/ext/diffequations.o

# target to preprocess a source file
src/ext/diffequations.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/diffequations.i
.PHONY : src/ext/diffequations.i

# target to generate assembly for a file
src/ext/diffequations.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/diffequations.s
.PHONY : src/ext/diffequations.s

# target to build an object file
src/ext/fasttransforms.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/fasttransforms.o
.PHONY : src/ext/fasttransforms.o

# target to preprocess a source file
src/ext/fasttransforms.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/fasttransforms.i
.PHONY : src/ext/fasttransforms.i

# target to generate assembly for a file
src/ext/fasttransforms.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/fasttransforms.s
.PHONY : src/ext/fasttransforms.s

# target to build an object file
src/ext/integration.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/integration.o
.PHONY : src/ext/integration.o

# target to preprocess a source file
src/ext/integration.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/integration.i
.PHONY : src/ext/integration.i

# target to generate assembly for a file
src/ext/integration.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/integration.s
.PHONY : src/ext/integration.s

# target to build an object file
src/ext/interpolation.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/interpolation.o
.PHONY : src/ext/interpolation.o

# target to preprocess a source file
src/ext/interpolation.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/interpolation.i
.PHONY : src/ext/interpolation.i

# target to generate assembly for a file
src/ext/interpolation.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/interpolation.s
.PHONY : src/ext/interpolation.s

# target to build an object file
src/ext/linalg.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/linalg.o
.PHONY : src/ext/linalg.o

# target to preprocess a source file
src/ext/linalg.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/linalg.i
.PHONY : src/ext/linalg.i

# target to generate assembly for a file
src/ext/linalg.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/linalg.s
.PHONY : src/ext/linalg.s

# target to build an object file
src/ext/optimization.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/optimization.o
.PHONY : src/ext/optimization.o

# target to preprocess a source file
src/ext/optimization.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/optimization.i
.PHONY : src/ext/optimization.i

# target to generate assembly for a file
src/ext/optimization.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/optimization.s
.PHONY : src/ext/optimization.s

# target to build an object file
src/ext/solvers.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/solvers.o
.PHONY : src/ext/solvers.o

# target to preprocess a source file
src/ext/solvers.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/solvers.i
.PHONY : src/ext/solvers.i

# target to generate assembly for a file
src/ext/solvers.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/solvers.s
.PHONY : src/ext/solvers.s

# target to build an object file
src/ext/specialfunctions.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/specialfunctions.o
.PHONY : src/ext/specialfunctions.o

# target to preprocess a source file
src/ext/specialfunctions.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/specialfunctions.i
.PHONY : src/ext/specialfunctions.i

# target to generate assembly for a file
src/ext/specialfunctions.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/specialfunctions.s
.PHONY : src/ext/specialfunctions.s

# target to build an object file
src/ext/statistics.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/statistics.o
.PHONY : src/ext/statistics.o

# target to preprocess a source file
src/ext/statistics.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/statistics.i
.PHONY : src/ext/statistics.i

# target to generate assembly for a file
src/ext/statistics.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/ext/statistics.s
.PHONY : src/ext/statistics.s

# target to build an object file
src/inverse.o:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/inverse.o
.PHONY : src/inverse.o

# target to preprocess a source file
src/inverse.i:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/inverse.i
.PHONY : src/inverse.i

# target to generate assembly for a file
src/inverse.s:
	$(MAKE) -f CMakeFiles/inverse.out.dir/build.make CMakeFiles/inverse.out.dir/src/inverse.s
.PHONY : src/inverse.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... inverse.out"
	@echo "... src/BVHData.o"
	@echo "... src/BVHData.i"
	@echo "... src/BVHData.s"
	@echo "... src/c_butterworth/c_butterworth.o"
	@echo "... src/c_butterworth/c_butterworth.i"
	@echo "... src/c_butterworth/c_butterworth.s"
	@echo "... src/c_butterworth/rtGetInf.o"
	@echo "... src/c_butterworth/rtGetInf.i"
	@echo "... src/c_butterworth/rtGetInf.s"
	@echo "... src/c_butterworth/rtGetNaN.o"
	@echo "... src/c_butterworth/rtGetNaN.i"
	@echo "... src/c_butterworth/rtGetNaN.s"
	@echo "... src/c_butterworth/rt_nonfinite.o"
	@echo "... src/c_butterworth/rt_nonfinite.i"
	@echo "... src/c_butterworth/rt_nonfinite.s"
	@echo "... src/ext/alglibinternal.o"
	@echo "... src/ext/alglibinternal.i"
	@echo "... src/ext/alglibinternal.s"
	@echo "... src/ext/alglibmisc.o"
	@echo "... src/ext/alglibmisc.i"
	@echo "... src/ext/alglibmisc.s"
	@echo "... src/ext/ap.o"
	@echo "... src/ext/ap.i"
	@echo "... src/ext/ap.s"
	@echo "... src/ext/dataanalysis.o"
	@echo "... src/ext/dataanalysis.i"
	@echo "... src/ext/dataanalysis.s"
	@echo "... src/ext/diffequations.o"
	@echo "... src/ext/diffequations.i"
	@echo "... src/ext/diffequations.s"
	@echo "... src/ext/fasttransforms.o"
	@echo "... src/ext/fasttransforms.i"
	@echo "... src/ext/fasttransforms.s"
	@echo "... src/ext/integration.o"
	@echo "... src/ext/integration.i"
	@echo "... src/ext/integration.s"
	@echo "... src/ext/interpolation.o"
	@echo "... src/ext/interpolation.i"
	@echo "... src/ext/interpolation.s"
	@echo "... src/ext/linalg.o"
	@echo "... src/ext/linalg.i"
	@echo "... src/ext/linalg.s"
	@echo "... src/ext/optimization.o"
	@echo "... src/ext/optimization.i"
	@echo "... src/ext/optimization.s"
	@echo "... src/ext/solvers.o"
	@echo "... src/ext/solvers.i"
	@echo "... src/ext/solvers.s"
	@echo "... src/ext/specialfunctions.o"
	@echo "... src/ext/specialfunctions.i"
	@echo "... src/ext/specialfunctions.s"
	@echo "... src/ext/statistics.o"
	@echo "... src/ext/statistics.i"
	@echo "... src/ext/statistics.s"
	@echo "... src/inverse.o"
	@echo "... src/inverse.i"
	@echo "... src/inverse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

